var tigger = { character: "Tigger"};
var pooh = { character: "Winnie the Pooh"}
var piglet = { character: "Piglet"};
var bees = { character: "Bees"};
var owl = { character: "Owl"};
var chris = { character: "Christopher Robin"};
var rabbit = { character: "Rabbit"};
var gopher = { character: "Gopher"};
var kanga = { character: "Kanga"};
var eeyore = { character: "Eeyore"};
var heffa = { character: "Heffalumps"};
tigger.north = pooh
pooh.west = piglet;
pooh.east = bees;
pooh.north = chris;
pooh.south = tigger;
piglet.east = pooh;
piglet.north = owl;
bees.east = pooh;
bees.north = rabbit;
owl.south = piglet;
owl.east = chris;
chris.west = owl;
chris.east = rabbit;
chris.north = kanga;
chris.south = pooh;
rabbit.south = bees;
rabbit.east = gopher;
rabbit.west = chris;
gopher.west = rabbit;
kanga.south = chris;
kanga.north = eeyore;
eeyore.south = kanga;
eeyore.east = heffa;
heffa.east = eeyore;

